version: '3.8'
services:
  mongodb:
    image: mongo:latest
    command: mongod --port 27018
    env_file:
      - .env.docker
    ports:
      - 27018:27018
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:prod
    env_file:
      - .env.docker
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: